language: node_js

node_js:
    - "stable"

env:
    - NODE_ENV="development"
#    - NODE_ENV="production"; SECRET="something"

before_script:
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - npm install

script: gulp travis

sudo: false

dist: trusty

#
# deploy:
#   provider: s3
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#   bucket: $BUCKET_NAME
#   skip_cleanup: true
#   local_dir: build
#   upload-dir: cesium-website/$TRAVIS_BRANCH
#   on:
#     all_branches: true
