# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Now UI Dashboard PRO
description: Now UI Dashboard PRO by Creative Tim
twitter: CreativeTim
authors: Creative Tim
email: your-email@domain.com
encoding:         UTF-8
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
destination:      ./_gh_pages
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.creative-tim.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

plugins_dir:
  - jekyll-toc

product_name: Now UI Dashboard PRO
product_slug: now-ui-dashboard-pro

# Build settings
markdown: kramdown

exclude: [.git, .github, assets/scss/, assets/main.css, build, js, node_modules, nuget, scss, vendor, bower.json, composer.json, Gemfile, Gemfile.lock, Gruntfile.js, package.js, package.json, package-lock.json, sache.json, dist, CONTRIBUTING.md, deploy.sh, HACKING.md, ISSUE_TEMPLATE.md, LICENSE.md, rollup.config.js, yarn.lock, about, gulpfile.js, gulp_archive ]

current_version:  1.0.0
docs_version:     1.0
repo:             https://github.com/creativetimofficial/now-ui-dashboard-pro

download:
  source:         https://github.com/creativetimofficial/now-ui-dashboard-pro
  dist:           https://github.com/creativetimofficial/now-ui-dashboard-pro/archive/v1.0.0.zip
